"""workspace litellm_key_alias

Revision ID: 8325c715e6e2
Revises: 749781f6af9b
Create Date: 2026-07-01 00:33:02.047255
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8325c715e6e2'
down_revision: str | None = '749781f6af9b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('litellm_key_alias', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_column('litellm_key_alias')

    # ### end Alembic commands ###
