#!/usr/bin/env bash
# Runtime setup for the seko workspace image.
#
# The mounted /home/dev volume is durable and may be empty on first boot, so anything the
# user needs at runtime is created idempotently here: authorized_keys, LLM env files, pi's
# config directory, and persistent SSH host keys.
set -euo pipefail

DEV_USER="dev"
DEV_GROUP="dev"
DEV_HOME="/home/dev"
SSH_DIR="${DEV_HOME}/.ssh"
SEKO_CONFIG_DIR="${DEV_HOME}/.config/seko"
LLM_ENV_FILE="${SEKO_CONFIG_DIR}/llm.env"
PROFILE_D_FILE="/etc/profile.d/seko-llm.sh"
ETC_ENVIRONMENT="/etc/environment"
AUTHORIZED_KEYS_FILE="${SSH_DIR}/authorized_keys"
SECRETS_AUTHORIZED_KEYS="/run/secrets/authorized_keys"
MANAGED_START="# BEGIN seko workspace managed block"
MANAGED_END="# END seko workspace managed block"

log() {
  printf '[seko-entrypoint] %s\n' "$*" >&2
}

shell_quote() {
  printf "'"
  printf '%s' "$1" | sed "s/'/'\\\\''/g"
  printf "'"
}

environment_quote() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

replace_managed_block() {
  local file="$1"
  local tmp="${file}.seko.$$"

  touch "$file"
  awk -v start="$MANAGED_START" -v end="$MANAGED_END" '
    $0 == start { skip = 1; next }
    $0 == end { skip = 0; next }
    !skip { print }
  ' "$file" > "$tmp"

  {
    cat "$tmp"
    printf '%s\n' "$MANAGED_START"
    cat
    printf '%s\n' "$MANAGED_END"
  } > "$file"
  rm -f "$tmp"
}

ensure_home_layout() {
  log "ensuring ${DEV_HOME} runtime directories exist"
  # The mount root is owned by seko(1001)=dev(1001); tolerate if the FUSE root rejects chown.
  install -d -o "${DEV_USER}" -g "${DEV_GROUP}" -m 0755 "${DEV_HOME}" 2>/dev/null \
    || { mkdir -p "${DEV_HOME}"; chmod 0755 "${DEV_HOME}" 2>/dev/null || true; }
  install -d -o "${DEV_USER}" -g "${DEV_GROUP}" -m 0700 "${SSH_DIR}"
  install -d -o "${DEV_USER}" -g "${DEV_GROUP}" -m 0755 "${SEKO_CONFIG_DIR}"
  install -d -o "${DEV_USER}" -g "${DEV_GROUP}" -m 0755 "${DEV_HOME}/workspace" "${DEV_HOME}/.pi/agent"
  install -d -m 0755 /run/sshd
}

write_authorized_keys() {
  local raw_keys="${AUTHORIZED_KEYS_FILE}.raw.$$"
  local normalized_keys="${AUTHORIZED_KEYS_FILE}.normalized.$$"
  : > "${raw_keys}"

  if [ -n "${SEKO_AUTHORIZED_KEYS:-}" ]; then
    log "loading authorized keys from SEKO_AUTHORIZED_KEYS"
    printf '%s\n' "${SEKO_AUTHORIZED_KEYS}" >> "${raw_keys}"
  fi

  if [ -f "${SECRETS_AUTHORIZED_KEYS}" ]; then
    log "loading authorized keys from ${SECRETS_AUTHORIZED_KEYS}"
    cat "${SECRETS_AUTHORIZED_KEYS}" >> "${raw_keys}"
    printf '\n' >> "${raw_keys}"
  fi

  sed 's/\r$//' "${raw_keys}" | awk 'NF { print }' > "${normalized_keys}"

  if [ ! -s "${normalized_keys}" ]; then
    log "WARNING: no authorized keys provided; SSH login for dev will be unavailable"
  fi

  install -o "${DEV_USER}" -g "${DEV_GROUP}" -m 0600 "${normalized_keys}" "${AUTHORIZED_KEYS_FILE}"
  rm -f "${raw_keys}" "${normalized_keys}"
}

ensure_host_keys() {
  # sshd requires root-owned host keys, but a gocryptfs mount (served by the unprivileged
  # seko user) can't hold root-owned files. So keep host keys in /etc/ssh (container fs,
  # root-owned). They persist across stop/start; a terminate+recreate regenerates them
  # (a restored workspace is a new container, so a changed fingerprint is expected).
  if [ ! -s /etc/ssh/ssh_host_ed25519_key ]; then
    log "generating SSH host keys in /etc/ssh"
    ssh-keygen -A >/dev/null
  else
    log "using existing /etc/ssh host keys"
  fi
}

write_llm_env() {
  local llm_base_url="${LLM_BASE_URL:-${OPENAI_BASE_URL:-}}"
  local llm_api_key="${LLM_API_KEY:-${OPENAI_API_KEY:-}}"
  local llm_model="${LLM_MODEL:-${OPENAI_MODEL:-}}"

  export LLM_BASE_URL="${llm_base_url}"
  export LLM_API_KEY="${llm_api_key}"
  export LLM_MODEL="${llm_model}"
  export OPENAI_BASE_URL="${llm_base_url}"
  export OPENAI_API_KEY="${llm_api_key}"
  export OPENAI_MODEL="${llm_model}"

  log "writing LLM environment for dev shells and pi"
  {
    printf '# Generated by seko-entrypoint; do not commit.\n'
    printf 'export LLM_BASE_URL=%s\n' "$(shell_quote "${LLM_BASE_URL}")"
    printf 'export LLM_API_KEY=%s\n' "$(shell_quote "${LLM_API_KEY}")"
    printf 'export LLM_MODEL=%s\n' "$(shell_quote "${LLM_MODEL}")"
    printf 'export OPENAI_BASE_URL=%s\n' "$(shell_quote "${OPENAI_BASE_URL}")"
    printf 'export OPENAI_API_KEY=%s\n' "$(shell_quote "${OPENAI_API_KEY}")"
    printf 'export OPENAI_MODEL=%s\n' "$(shell_quote "${OPENAI_MODEL}")"
  } > "${LLM_ENV_FILE}"
  chown "${DEV_USER}:${DEV_GROUP}" "${LLM_ENV_FILE}"
  chmod 0600 "${LLM_ENV_FILE}"

  {
    printf '# Generated by seko-entrypoint; sourced by login shells.\n'
    printf '[ -r %s ] && . %s\n' "$(shell_quote "${LLM_ENV_FILE}")" "$(shell_quote "${LLM_ENV_FILE}")"
  } > "${PROFILE_D_FILE}"
  chown root:"${DEV_GROUP}" "${PROFILE_D_FILE}"
  chmod 0640 "${PROFILE_D_FILE}"

  replace_managed_block "${ETC_ENVIRONMENT}" <<EOF_ENVIRONMENT
LLM_BASE_URL="$(environment_quote "${LLM_BASE_URL}")"
LLM_API_KEY="$(environment_quote "${LLM_API_KEY}")"
LLM_MODEL="$(environment_quote "${LLM_MODEL}")"
OPENAI_BASE_URL="$(environment_quote "${OPENAI_BASE_URL}")"
OPENAI_API_KEY="$(environment_quote "${OPENAI_API_KEY}")"
OPENAI_MODEL="$(environment_quote "${OPENAI_MODEL}")"
EOF_ENVIRONMENT
  chmod 0644 "${ETC_ENVIRONMENT}"
}

ensure_shell_sources() {
  local rc
  for rc in "${DEV_HOME}/.bashrc" "${DEV_HOME}/.profile"; do
    if [ ! -e "${rc}" ]; then
      : > "${rc}"
      chown "${DEV_USER}:${DEV_GROUP}" "${rc}"
      chmod 0644 "${rc}"
    fi
    replace_managed_block "${rc}" <<EOF_SHELL_SOURCE
[ -r "\${HOME}/.config/seko/llm.env" ] && . "\${HOME}/.config/seko/llm.env"
EOF_SHELL_SOURCE
    chown "${DEV_USER}:${DEV_GROUP}" "${rc}"
    chmod 0644 "${rc}"
  done
}

install_pi_config() {
  # Install pi's config into the mounted ~/.pi/agent (baked config lives outside the mount).
  # The local-llm provider extension is MANAGED — always refreshed so fixes propagate.
  # settings.json is SEEDED once (users may tweak it); defaultModel tracks LLM_MODEL.
  local src="/usr/local/share/seko-pi"
  local agent="${DEV_HOME}/.pi/agent"
  install -d -o "${DEV_USER}" -g "${DEV_GROUP}" -m 0755 "${agent}/extensions"

  if [ -f "${src}/local-llm.ts" ]; then
    log "installing pi local-llm provider extension"
    install -o "${DEV_USER}" -g "${DEV_GROUP}" -m 0644 \
      "${src}/local-llm.ts" "${agent}/extensions/local-llm.ts"
  fi

  if [ ! -e "${agent}/settings.json" ] && [ -f "${src}/settings.json" ]; then
    log "seeding pi settings.json (defaultModel=${LLM_MODEL:-qwen3.6-27b})"
    sed "s/\"defaultModel\": \"[^\"]*\"/\"defaultModel\": \"${LLM_MODEL:-qwen3.6-27b}\"/" \
      "${src}/settings.json" > "${agent}/settings.json"
    chown "${DEV_USER}:${DEV_GROUP}" "${agent}/settings.json"
    chmod 0644 "${agent}/settings.json"
  fi
}

main() {
  ensure_home_layout
  write_authorized_keys
  ensure_host_keys
  write_llm_env
  ensure_shell_sources
  install_pi_config

  if [ "$#" -eq 0 ]; then
    set -- /usr/sbin/sshd -D -e
  fi

  log "executing: $*"
  exec "$@"
}

main "$@"
